### ISSUE TITLE
Prism version

### ISSUE THREAD

**Issue by melsawy93** [HellPie/HellPie.Revit.PrismDemo#2]
I have implemented Prism with other software similar to Revit. I am looking into using it for Revit. This seems to be done 2 years ago and I know Prism has changed alot during those years. Do you happen to have a more up-to-date template using Prism in Revit plugins?

Thanks!

**Comment by HellPie** [comment]
Nope sorry I left the company I worked for two years ago and with that I also left behind Revit entirely.
